Repository VirtusLab/git-machete, pull requests merged in 2021-10, with the labels that each got.

#255 Issue #251: Remove direct run_git and popen_git calls from client.py.
  git_machete/client.py
  git_machete/constants.py
  git_machete/git_operations.py
Labels: bug, code quality, underlying git

#260 Remove messages returned by git in tests
  git_machete/tests/functional/test_machete.py
Labels: testing

#262 Check PEP8 correctness for one python version in CI
  .circleci/config.yml
  ci/tox/Dockerfile
  ci/tox/build-context/entrypoint.sh
  ci/tox/docker-compose.yml
Labels: ci
