Repository VirtusLab/git-machete, pull requests merged in 2021-09, with the labels that each got.

#200 Issue #174: Uncomment remaining links.
  CONTRIBUTING.md
Labels: docs

#208 Adding Guidelines about PR's and Git usage in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#209 Move instructions for shell completion from Wiki into docs
  README.md
  completion/README.md
Labels: docs

#212 Refactor 1-2 letter variable names to be more descriptive
  git_machete/cmd.py
  git_machete/git_operations.py
Labels: code

#202 Create documentation with sphinx aiming for putting it later on the reathedocs
  .circleci/config.yml
  .gitignore
  ci/checks/enforce-indent-two-spaces-outside-python.sh
  ci/tox/Dockerfile
  ci/tox/build-context/entrypoint.sh
  ci/tox/docker-compose.yml
  docs/source/cli.rst
  docs/source/cli_help/add.rst
  docs/source/cli_help/advance.rst
  docs/source/cli_help/anno.rst
  docs/source/cli_help/delete-unmanaged.rst
  docs/source/cli_help/diff.rst
  docs/source/cli_help/discover.rst
  docs/source/cli_help/edit.rst
  docs/source/cli_help/file.rst
  docs/source/cli_help/fork-point.rst
  docs/source/cli_help/format.rst
  docs/source/cli_help/github.rst
  docs/source/cli_help/go.rst
  docs/source/cli_help/help.rst
  docs/source/cli_help/hooks.rst
  docs/source/cli_help/is-managed.rst
  docs/source/cli_help/list.rst
  docs/source/cli_help/log.rst
  docs/source/cli_help/reapply.rst
  docs/source/cli_help/show.rst
  docs/source/cli_help/slide-out.rst
  docs/source/cli_help/squash.rst
  docs/source/cli_help/status.rst
  docs/source/cli_help/traverse.rst
  docs/source/cli_help/update.rst
  docs/source/cli_help/version.rst
  docs/source/completion.rst
  docs/source/conf.py
  docs/source/description.rst
  docs/source/index.rst
  docs/source/learning_materials.rst
  git_machete/docs.py
  tox.ini
Labels: docs

#217 Add references to Read the Docs in README.md, CONTRIBUTING.md etc.
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
Labels: docs

#219 get remote git url from config
  git_machete/git_operations.py
Labels: bug, minor

#215 Issue #206: Split current cmd.py into client.py and cli.py
  git-machete
  git_machete/cli.py
  git_machete/client.py
  git_machete/constants.py
  git_machete/git_operations.py
  git_machete/tests/functional/test_machete.py
  git_machete/utils.py
Labels: code, cli

#224 Issue #221: Fix logo rendering.
  README.md
Labels: bug, docs

#225 Issue #222: Fix the gap in snippet in Docker part 2 blog.
  blogs/docker-ci-tricks-2/blog.md
Labels: bug, docs

#214 Add regression tests for github methods
  README.md
  git_machete/cli.py
  git_machete/client.py
  git_machete/github.py
  git_machete/tests/functional/test_machete.py
Labels: testing, github

#205 Introduce github checkout-pr command
  CONTRIBUTING.md
  README.md
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  docs/source/cli_help/github.rst
  git_machete/cli.py
  git_machete/client.py
  git_machete/docs.py
  git_machete/git_operations.py
  git_machete/github.py
  git_machete/tests/functional/test_machete.py
  git_machete/utils.py
Labels: feature, github

#230 add check if head and base branch are equal
  git_machete/client.py
  git_machete/tests/functional/test_machete.py
Labels: bug, github

#241 Separate mypy checks into own tox env
  ci/tox/build-context/entrypoint.sh
  tox.ini
Labels: build

#229 Issue #158: Migrate CLI to argparse.
  git_machete/cli.py
  git_machete/options.py
  git_machete/tests/functional/test_machete.py
  git_machete/utils.py
Labels: cli

#247 Fix for TypeError when token is available
  git_machete/client.py
  git_machete/tests/functional/test_machete.py
Labels: bug, testing, severe

#240 Remove `n` option when selecting remote repository while creating github pull requests
  git_machete/cli.py
  git_machete/client.py
  git_machete/exceptions.py
Labels: bug, github

#250 Issue #235: Correct slide-out documentation
  docs/source/cli_help/slide-out.rst
  git_machete/docs.py
Labels: docs

#248 Allow to checkout closed pull requests
  git_machete/client.py
  git_machete/github.py
  git_machete/tests/functional/test_machete.py
Labels: github, usability

#249 Issue #237: Improve cache management
  git_machete/client.py
  git_machete/git_operations.py
Labels: bug, underlying git

#253 Issue #234: Fix how some command's options appear on readthedocs.
  docs/source/cli_help/add.rst
  docs/source/cli_help/advance.rst
  docs/source/cli_help/anno.rst
  docs/source/cli_help/delete-unmanaged.rst
  docs/source/cli_help/diff.rst
  docs/source/cli_help/discover.rst
  docs/source/cli_help/github.rst
  docs/source/cli_help/reapply.rst
  docs/source/cli_help/slide-out.rst
  docs/source/cli_help/squash.rst
  docs/source/cli_help/status.rst
  docs/source/cli_help/traverse.rst
  docs/source/cli_help/update.rst
Labels: bug, docs

#252 Issue #238: Fix github create-pr command behaviour.
  git_machete/client.py
Labels: bug, python api

#256 fix for `u` alias in `go` command
  git_machete/client.py
  git_machete/tests/functional/test_machete.py
Labels: bug, cli

#258 Enable pypistats.org badge
  README.md
Labels: minor, ci

#257 enforce correct shebags in CI
  .circleci/config.yml
  ci/checks/enforce-correct-shebangs.sh
  git-machete
  git_machete/cli.py
  git_machete/github.py
  setup.py
Labels: ci
