Repository VirtusLab/git-machete, pull requests merged in 2021-11, with the labels that each got.

#327 Issue #309 : Wrong remote selected in `checkout-prs`
  git_machete/client.py
  git_machete/tests/functional/test_machete.py
Labels: bug, github, usability

#326 Issues #290 and #315: Finishing touches to fish completion.
  ci/checks/ensure-completion-scripts-correct.sh
  completion/README.md
  completion/git-machete.fish
  docs/source/completion.rst
Labels: cli

#330 Issue #328: Bugfix - mistyped CommandLineOptions.opt_branch
  git_machete/cli.py
  git_machete/tests/functional/test_machete.py
Labels: bug, cli, severe

#331 Issue #318: Enhance traverse message when no action is done
  docs/source/cli_help/traverse.rst
  git_machete/client.py
  git_machete/docs.py
Labels: docs, traverse, usability

#336 Issue #332: Hide traceback from UnprocessableEntity error
  git_machete/exceptions.py
  git_machete/github.py
Labels: minor, cli

#338 Do not flush `__tree_sha_by_commit_sha_cached`, `__merge_base_cached`, `__contains_equivalent_tree`
  git_machete/__init__.py
  git_machete/client.py
  git_machete/git_operations.py
Labels: code quality, performance, underlying git

#346 Issue #345: Better handling of error messages from `UnprocessableEntityError`
  git_machete/github.py
Labels: bug, github

#341 Issue #334: install git-machete locally from freshly generated brew formula
  .circleci/config.yml
  ci/homebrew-tap/ci-deploy.sh
Labels: testing, build, ci

#348 Issue #335: Check if base branch for PR exists on remote
  git_machete/client.py
  git_machete/tests/functional/test_machete.py
Labels: github, usability

#347 Issue #177: Enchance error message when assigning reviewers from outside organisation
  git_machete/client.py
Labels: github, usability

#350 Remove check if pull requests is already created
  git_machete/exceptions.py
  git_machete/github.py
  git_machete/tests/functional/test_machete.py
Labels: performance, github, usability

#352 issue #:312Remove `yq` installation from CI
  .circleci/config.yml
Labels: minor, ci

#351 Issue #316: Introduce ForkPointOverrideData type
  git_machete/client.py
  git_machete/git_operations.py
Labels: code quality

#353 Issue #134: Add t alias for traverse command
  RELEASE_NOTES.md
  docs/source/cli_help/traverse.rst
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/docs.py
  git_machete/tests/functional/test_machete.py
Labels: minor, cli

#357 Issue #356: Allow ShortCommitHash type to have length greater than 7 characters
  RELEASE_NOTES.md
  git_machete/git_operations.py
Labels: bug, severe

#358 Issue #355: Remove newline in message while adding reviewers to created pull request
  git_machete/client.py
Labels: bug, minor

#367 Replaced older System I/O with print
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/client.py
  git_machete/git_operations.py
  git_machete/tests/functional/test_machete.py
  git_machete/utils.py
Labels: code quality

#369 Fix dry runs of Homebrew tap update
  ci/homebrew-tap/ci-deploy.sh
Labels: bug, distribute, build
