Repository VirtusLab/git-machete, pull requests merged in 2021-08, with the labels that each got.

#159 Split cmd.py into smaller modules
  git_machete/cmd.py
  git_machete/constants.py
  git_machete/docs.py
  git_machete/exceptions.py
  git_machete/git_operations.py
  git_machete/options.py
  git_machete/tests/functional/test_machete.py
  git_machete/utils.py
Labels: code

#166 Ensure version is bumped in __init__.py
  .circleci/config.yml
  ci/checks/ensure-version-bumped.sh
Labels: ci

#167 Tests for go, show, update and advance
  git_machete/tests/functional/test_machete.py
Labels: testing

#168 Add private and protected fields
  git_machete/cmd.py
  git_machete/git_operations.py
Labels: code

#130 Add `hub` command for GitHub operations
  CONTRIBUTING.md
  README.md
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  git_machete/__init__.py
  git_machete/cmd.py
  git_machete/docs.py
  git_machete/exceptions.py
  git_machete/github.py
  git_machete/options.py
  git_machete/utils.py
Labels: enhancement, github

#180 Issue #142: Add test coverage reporting tool to CI of git-machete.
  .circleci/config.yml
  .gitignore
  ci/tox/Dockerfile
  ci/tox/build-context/entrypoint.sh
  ci/tox/docker-compose.yml
  debian/source/options
  tox.ini
Labels: testing, build, ci

#179 Fix wrong line number when branch reappears in definition file && limit stack trace in certain Exceptions
  git_machete/cmd.py
  git_machete/tests/functional/test_machete.py
Labels: bug, minor

#187 Issue #146 Optimise tests in CI to shorten the execution.
  .circleci/config.yml
  ci/tox/Dockerfile
  ci/tox/build-context/entrypoint.sh
Labels: performance, ci

#182 Extract generic code across ci scripts
  .circleci/config.yml
  ci/deb-ppa-upload/ci-deploy.sh
  ci/deb-ppa-upload/local-run.sh
  ci/docker-build-and-push.sh
  ci/local-run-commons.sh
  ci/rpm/ci-run.sh
  ci/rpm/local-run.sh
  ci/tox/Dockerfile
  ci/tox/ci-run.sh
  ci/tox/local-run.sh
Labels: code, ci

#197 call export_directory_hash instead of export_hash in local_run scripts.
  ci/deb-ppa-upload/export-gpg-ssh-config
  ci/deb-ppa-upload/local-run.sh
  ci/rpm/local-run.sh
  ci/tox/local-run.sh
Labels: bug

#194 Issue #174: Move content of Docker CI setup blog to git-machete repo and update it.
  CONTRIBUTING.md
  README.md
  blogs/docker-ci-tricks-1/blog.md
  blogs/docker-ci-tricks-1/docker-images.png
  blogs/docker-ci-tricks-1/project-layout.png
  blogs/docker-ci-tricks-2/blog.md
  blogs/docker-ci-tricks-2/root-owned-folders.png
  blogs/docker-ci-tricks-2/user-owned-folders.png
  blogs/git-machete-1/blog-1.md
  blogs/git-machete-1/gitk-0.png
  blogs/git-machete-1/gitk-1.png
  blogs/git-machete-1/gitk-2.png
  blogs/git-machete-1/sandbox-setup-reduced.sh
  blogs/git-machete-1/sandbox-setup.sh
  blogs/git-machete-1/slide-out.png
  blogs/git-machete-1/status-1.png
  blogs/git-machete-1/status-2.png
  blogs/git-machete-1/status-l-1.png
  blogs/git-machete-1/status-l-3.png
  blogs/git-machete-1/update-2.png
  blogs/git-machete-1/update.png
  blogs/git-machete-2/add.png
  blogs/git-machete-2/blog-2.md
  blogs/git-machete-2/discover.png
  blogs/git-machete-2/sandbox-setup-2.sh
  blogs/git-machete-2/show-up-go-up.png
  blogs/git-machete-2/status.png
  blogs/git-machete-2/traverse.png
  blogs/git-machete-2/update-3.png
  ci/checks/enforce-indent-two-spaces-outside-python.sh
  docs/blog-2/files-changed.png
  graphics/discover-status-traverse.gif
  graphics/generate-asciinema-gif
  graphics/logo.png
  graphics/logo_with_name.svg
  graphics/setup-sandbox
Labels: docs

#198 Issue #174: Uncommenting links, so blogs have full content available.
  CONTRIBUTING.md
  README.md
  blogs/git-machete-1/blog.md
  blogs/git-machete-2/blog.md
Labels: docs
