Repository VirtusLab/git-machete, pull requests merged in 2022-04, with the labels that each got.

#476 Determine whether a rebase/merge/revert/cherry-pick is ongoing on per-worktree basis
  RELEASE_NOTES.md
  docs/source/cli_help/hooks.rst
  git_machete/client.py
  git_machete/docs.py
  git_machete/git_operations.py
  git_machete/tests/functional/test_machete.py
Labels: bug, underlying git

#469 Issue #468: Display a more verbose message when GITHUB_TOKEN env variable is missing
  git_machete/client.py
  git_machete/github.py
Labels: code quality

#435 Issue #433: Add new command `git machete clean`
  README.md
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  completion/git-machete.fish
  docs/source/cli.rst
  docs/source/cli_help/anno.rst
  docs/source/cli_help/clean.rst
  docs/source/cli_help/github.rst
  docs/source/cli_help/slide-out.rst
  docs/source/conf.py
  docs/source/github_api_access.rst
  git_machete/cli.py
  git_machete/client.py
  git_machete/docs.py
  git_machete/git_operations.py
  git_machete/github.py
  git_machete/options.py
  git_machete/tests/functional/test_machete.py
  git_machete/utils.py
Labels: feature, github

#485 Issue #478: `git machete github checkout-prs` accepts again --verbose or --debug options
  git_machete/cli.py
Labels: bug, cli

#483 Issue #474: When using `git machete github checkout-prs --by=...` switch current head branch only when one PR is checked out
  docs/source/cli_help/github.rst
  git_machete/cli.py
  git_machete/client.py
  git_machete/docs.py
  git_machete/git_operations.py
  git_machete/tests/functional/test_machete.py
Labels: bug, github

#482 Issue #470 + #454: Use consistent fork point/fork_point/GitHub style everywhere
  CONTRIBUTING.md
  ci/checks/ensure-consistent-style-for-fork-point.sh
  ci/checks/ensure-consistent-style-for-github.sh
  ci/checks/utils.sh
  completion/git-machete.completion.zsh
  completion/git-machete.fish
  docs/source/cli.rst
  docs/source/cli_help/clean.rst
  docs/source/cli_help/github.rst
  git_machete/cli.py
  git_machete/client.py
  git_machete/docs.py
  git_machete/exceptions.py
  git_machete/git_operations.py
  git_machete/tests/functional/test_machete.py
  hook_samples/machete-post-slide-out
Labels: code quality

#488 3.8.0 release fixes
  ci/checks/ensure-consistent-style-for-fork-point.sh
  completion/git-machete.completion.bash
  docs/source/cli.rst
  docs/source/cli_help/github.rst
  git_machete/docs.py
Labels: release

#480 Refactor code around `GitContext.is_equivalent_tree_reachable`
  RELEASE_NOTES.md
  ci/github-releases/ci-deploy.sh
  git_machete/__init__.py
  git_machete/client.py
  git_machete/git_operations.py
Labels: code quality, underlying git

#481 `fork-point` no longer specially treats branches merged to its parent
  RELEASE_NOTES.md
  git_machete/client.py
Labels: fork point

#473 Issue #413: `advance` suggests a push to remote
  RELEASE_NOTES.md
  docs/source/cli_help/advance.rst
  git_machete/client.py
  git_machete/docs.py
  git_machete/tests/functional/test_machete.py
Labels: feature

#495 Improve docs, particularly for `traverse`
  .circleci/config.yml
  CONTRIBUTING.md
  ci/checks/prohibit-double-backticks-in-py.sh
  ci/checks/prohibit-single-backtick-in-rst.sh
  ci/checks/prohibit-trailing-whitespace.sh
  completion/git-machete.fish
  docs/source/cli.rst
  docs/source/cli_help/diff.rst
  docs/source/cli_help/fork-point.rst
  docs/source/cli_help/log.rst
  docs/source/cli_help/reapply.rst
  docs/source/cli_help/squash.rst
  docs/source/cli_help/status.rst
  docs/source/cli_help/traverse.rst
  docs/source/cli_help/update.rst
  git_machete/docs.py
  snap/snapcraft.yaml
Labels: docs, ci

#492 add codecov report and badge
  .circleci/config.yml
  README.md
Labels: testing, build

#500 test: separate common methods
  git_machete/tests/functional/commons.py
  git_machete/tests/functional/test_machete.py
Labels: code quality, testing

#502 test command `add`
  git_machete/tests/functional/test_add.py
  git_machete/tests/functional/test_machete.py
Labels: code quality, testing

#503 tests for `help`, `log`, `clean`
  git_machete/tests/functional/test_clean.py
  git_machete/tests/functional/test_help.py
  git_machete/tests/functional/test_log.py
  git_machete/tests/functional/test_machete.py
Labels: code quality, testing

#505 Tests for `github`
  git_machete/tests/functional/test_github.py
  git_machete/tests/functional/test_machete.py
Labels: code quality, testing
