Repository VirtusLab/git-machete, pull requests merged in 2022-07, with the labels that each got.

#570 Issue #569: Exclude all python sources from the trailing whitespace check
  RELEASE_NOTES.md
  ci/checks/prohibit-trailing-whitespace.sh
  git_machete/__init__.py
Labels: code quality

#558 Issue #553: `github retarget-pr` should take branch tracking data into account
  RELEASE_NOTES.md
  git_machete/client.py
  git_machete/git_operations.py
  tests/test_github.py
Labels: github

#566 Issue #565: `__get_inferred_counterpart_for_fetching_of_branch()` now correctly infers local branch's remote counterpart for fetching of branch when the branch is associated with more than one remote
  git_machete/git_operations.py
  tests/test_status.py
Labels: bug

#572 Issue #362: `GitRepositorySandbox.new_repo` has a side effect of changing the current directory
  tests/mockers.py
  tests/test_github.py
Labels: code quality, testing

#575 Issue #571: Tidy up trailing whitespaces after `|` in the output of `git machete status`
  git_machete/client.py
  tests/mockers.py
  tests/test_github.py
  tests/test_status.py
Labels: status

#578 Issue #576: Modify `create-pr` output
  git_machete/client.py
  tests/test_github.py
Labels: github

#577 Issue #573: Prioritise `origin` remote when inferring remote
  git_machete/client.py
  tests/test_github.py
Labels: github

#585 Minor visual fixes in tests
  RELEASE_NOTES.md
  git_machete/__init__.py
  tests/test_status.py
Labels: code quality, testing

#583 Fix bug in `traverse()` function where `self.managed_branches` were not updated properly after sliding out the branch
  git_machete/client.py
Labels: code quality, traverse

#579 Issue #509: Tidy up `client.status` function
  git_machete/cli.py
  git_machete/client.py
  git_machete/utils.py
  tests/test_status.py
Labels: status

#587 Issue #584: Update docs with conda installation and badge
  README.md
Labels: docs

#588 Issue #586: Enforce max line length in python files to 140
  git_machete/cli.py
  git_machete/client.py
  git_machete/exceptions.py
  git_machete/git_operations.py
  git_machete/github.py
  git_machete/utils.py
  tests/mockers.py
  tests/test_add.py
  tests/test_advance.py
  tests/test_anno.py
  tests/test_clean.py
  tests/test_diff.py
  tests/test_file.py
  tests/test_github.py
  tests/test_go.py
  tests/test_is_managed.py
  tests/test_log.py
  tests/test_show.py
  tests/test_slide_out.py
  tests/test_squash.py
  tests/test_status.py
  tests/test_traverse.py
  tests/test_update.py
  tox.ini
Labels: code quality

#591 Support GitHub remote URL in the form of `https://USERNAME@github.com/ORGANIZATION/REPOSITORY.git`
  RELEASE_NOTES.md
  git_machete/github.py
Labels: github

#601 Prevent a crash when a local branch uses another local branch as its remote tracking branch
  RELEASE_NOTES.md
  git_machete/__init__.py
  git_machete/git_operations.py
Labels: bug, underlying git

#594 Fix fork point being incorrectly inferred when parent branch has been pushed immediately after being created
  RELEASE_NOTES.md
  git_machete/client.py
  tests/test_status.py
Labels: bug, fork point, externally requested

#600 Add all existing png/svg versions of logo
  blogs/docker-ci-tricks-1/blog.md
  ci/checks/prohibit-tab-character.sh
  graphics/logo/png/128x128.png
  graphics/logo/png/256x256.png
  graphics/logo/png/32x32.png
  graphics/logo/png/512x512.png
  graphics/logo/png/64x64.png
  graphics/logo/svg/128x128.svg
  graphics/logo/svg/256x256.svg
  graphics/logo/svg/32x32.svg
  graphics/logo/svg/512x512.svg
  graphics/logo/svg/64x64.svg
  graphics/logo/svg/with-name.svg
  snap/snapcraft.yaml
Labels: docs

#602 Issue #595: Don't use formatting codes when output is not a terminal
  git_machete/cli.py
Labels: bug, usability

#606 Skip all newlines from the output of `machete-status-branch` hook to avoid messing up the rendered status
  RELEASE_NOTES.md
  git_machete/client.py
Labels: bug, status
