Repository VirtusLab/git-machete, pull requests merged in 2022-10, with the labels that each got.

#671 Issue #665: Remove package updates in tap from CI
  .circleci/config.yml
  CONTRIBUTING.md
  ci/homebrew-tap/ci-deploy.sh
Labels: ci

#674 Issue #665: Add automatic homebrew-core updates to CI
  .circleci/config.yml
  CONTRIBUTING.md
  README.md
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
Labels: distribute, ci

#676 Issue #665: Fix update to homebrew
  .circleci/config.yml
  ci/homebrew/ci-deploy.sh
Labels: bug, distribute, ci

#685 Fix release instructions, Fix homebrew update
  CONTRIBUTING.md
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
  git_machete/__init__.py
Labels: bug, docs, release

#687 Release v3.12.3
  CONTRIBUTING.md
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
  git_machete/__init__.py
Labels: release

#689 Release 3.12.4
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
  git_machete/__init__.py
Labels: release

#679 Issue #603: Print actual and expected value when assertion in the test fails
  RELEASE_NOTES.md
  git_machete/__init__.py
  tests/mockers.py
Labels: testing

#678 Issue #614: Tidy up error msg for `github create-pr`
  RELEASE_NOTES.md
  git_machete/client.py
Labels: minor, github

#683 Issue #605: Fix `utils.fmt()` function
  RELEASE_NOTES.md
  git_machete/utils.py
  tests/test_add.py
  tests/test_github.py
  tests/test_status.py
  tests/test_utils.py
Labels: bug

#670 Issue #560: Slow down the GIF in README
  CONTRIBUTING.md
  README.md
  RELEASE_NOTES.md
  graphics/discover-status-traverse.gif
  graphics/generate-asciinema-gif
  graphics/logo.png
Labels: docs

#698 Issue #690: Add retries on dry-run `brew install` in CI
  .circleci/config.yml
  ci/homebrew/ci-deploy.sh
Labels: bug, ci

#701 Issue #695: Generate short docs out of `docs/source/cli.rst`
  RELEASE_NOTES.md
  docs/enforce-docs-up-to-date.sh
  docs/generate_py_docs.py
  docs/source/cli.rst
  docs/source/short_docs.rst
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/generated_docs.py
  git_machete/handmade_short_docs.py
  tests/test_help.py
  tox.ini
Labels: docs, code quality

#702 Issue #657: Improve bullet point list's formatting in the python docs
  RELEASE_NOTES.md
  docs/generate_py_docs.py
  git_machete/generated_docs.py
Labels: docs

#704 Issue #653: Accept command aliases with `help` command
  RELEASE_NOTES.md
  git_machete/cli.py
  tests/test_cli.py
  tests/test_help.py
Labels: bug, cli

#703 Issue #646: Exit git machete command line process without stack trace when terminated with `Ctrl+D`
  RELEASE_NOTES.md
  git_machete/cli.py
Labels: cli

#706 Issue #705: Add `ExitCode` enum
  git_machete/cli.py
  git_machete/exceptions.py
  tests/mockers.py
  tests/test_help.py
Labels: code quality

#708 Issue #654: Add support for python 3.11
  .circleci/config.yml
  RELEASE_NOTES.md
  git_machete/__init__.py
  tox.ini
Labels: distribute

#712 Issue #645: Add `machete.traverse.push` config key with default value `true`
  RELEASE_NOTES.md
  docs/source/cli_help/config.rst
  docs/source/cli_help/traverse.rst
  docs/source/conf.py
  docs/source/traverse_config_key.rst
  git_machete/cli.py
  git_machete/generated_docs.py
  git_machete/git_operations.py
  tests/test_traverse.py
Labels: feature, traverse, externally requested

#574 Issue #557: `snapcraft: --with` is no longer supported, export the auth to the environment variable 'SNAPCRAFT_STORE_CREDENTIALS' instead
  ci/snap/ci-deploy.sh
Labels: distribute, on hold
