Repository VirtusLab/git-machete, pull requests merged in 2022-02, with the labels that each got.

#385 Issue #365: Check if release notes are updated with version bump
  .circleci/config.yml
  RELEASE_NOTES.md
  ci/checks/ensure-release-notes-up-to-date.sh
Labels: ci

#388 Issue #387: `github create-pr` takes the PR title from first unique commit
  RELEASE_NOTES.md
  git_machete/client.py
  git_machete/constants.py
  git_machete/git_operations.py
Labels: bug, github, usability

#391 Issue #389: Add remark config file to allow skipping URLs
  .remarkrc.yml
  .remarkrc_master.yml
  ci/checks/ensure-links-correct.sh
Labels: ci

#392 Issue #390: Use namedtuple instead of tuple for Hash_ShortHash_Message, BranchDef, ReflogEntry
  git_machete/client.py
  git_machete/git_operations.py
Labels: code quality

#404 Tidy up `tox` configuration
  requirements.txt
  test-requirements.txt
  tox.ini
Labels: code quality, testing, build

#405 Upload test results for viewing in the CI
  .circleci/config.yml
  .gitignore
  debian/source/options
  tox.ini
Labels: testing, ci

#415 Update docs & add badge for nixpkgs in README
  README.md
  ci/nixpkgs-build/local-run.sh
Labels: distribute

#418 Issue #417: Remove nix badge readme
  README.md
Labels: bug, docs

#431 Issue #364: Mock git_machete.github.__get_github_token inside test_github_create_pr_missing_base_branch_on_remote
  git_machete/tests/functional/test_machete.py
Labels: bug, testing

#354 Issue #231: Allow to checkout multiple PRs at once
  README.md
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  completion/git-machete.fish
  docs/source/cli_help/github.rst
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/client.py
  git_machete/docs.py
  git_machete/tests/functional/test_machete.py
Labels: feature, github

#416 Issue #393: Add support in zsh and bash completion for options of git machete github checkout-prs
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
Labels: cli

#440 Replace `deploy` steps with `run` steps in CircleCI config
  .circleci/config.yml
  ci/checks/prohibit-deploy-step-in-circleci.sh
Labels: ci, security

#449 Issue #448: Exclude https://github.com/r-ryantm from remark
  .remarkrc.yml
Labels: docs

#447 Issue #444: Use inspect.stack()[0].function in debug() in order to retrieve function name.
  git_machete/client.py
  git_machete/git_operations.py
  git_machete/github.py
  git_machete/utils.py
Labels: code quality
