Repository VirtusLab/git-machete, pull requests merged in 2022-11, with the labels that each got.

#718 Issue #711: Update docs with information that flag order defines their precedence over each other
  docs/enforce-docs-up-to-date.sh
  docs/source/cli_help/traverse.rst
  git_machete/generated_docs.py
Labels: docs

#723 Issue #719: Unify sphinx documentation formatting for config section
  RELEASE_NOTES.md
  docs/generate_py_docs.py
  docs/source/cli_help/config.rst
  docs/source/cli_help/status.rst
  docs/source/cli_help/traverse.rst
  docs/source/github_api_access.rst
  docs/source/github_config_keys.rst
  docs/source/status_config_key.rst
  docs/source/traverse_config_key.rst
  git_machete/generated_docs.py
Labels: docs

#728 Issue #707: Missing space after `Adding (...) to PR #(...)...`
  git_machete/client.py
Labels: github

#729 Issue #710: Display `config, hooks, format` in the output of `git machete help` and not in the output of `git machete`
  RELEASE_NOTES.md
  git_machete/cli.py
Labels: docs

#735 Issue #734: `git machete traverse -y --merge` does not work
  RELEASE_NOTES.md
  git_machete/cli.py
  tests/test_traverse.py
Labels: bug, traverse

#737 Issue #736: fix missing space
  git_machete/client.py
Labels: bug, minor, status

#738 Remove the dead link to .ignore plugin
  CONTRIBUTING.md
Labels: bug, docs
