Repository VirtusLab/git-machete, pull requests merged in 2022-03, with the labels that each got.

#450 Issue #438: Increase remark's network timeout in URL checks
  .remarkrc.yml
Labels: bug, ci

#456 Issue #446: Update tox.ini with information about flake8 configuration
  tox.ini
Labels: code quality

#451 Issue #443: git-machete should NOT always interactively ask about sliding out non-existent branches
  git_machete/cli.py
  git_machete/client.py
  git_machete/utils.py
Labels: bug

#459 Issue #458: Add link https://github.com/r-ryantm to remark's skipUrlPatterns
  .remarkrc.yml
Labels: bug

#455 Fixed GitHub Spelling
  CONTRIBUTING.md
  RELEASE_NOTES.md
  blogs/docker-ci-tricks-1/blog.md
  blogs/docker-ci-tricks-2/blog.md
  git_machete/github.py
Labels: docs, code quality

#429 Issue #428: Remove references to `stestr` after the update to Nix expression
  .stestr.conf
  ci/nixpkgs-build/build-context/entrypoint.sh
  debian/source/options
Labels: distribute, testing

#466 Issue #457 : Add shields.io to remark's skipUrlPatterns
  .remarkrc.yml
Labels: bug, ci

#463 Issue #462: `checkout_github_prs()` returns empty list when no PRs for the given criteria are found
  git_machete/client.py
  git_machete/tests/functional/test_machete.py
Labels: code quality

#453 Issue #436: Automate release of freshly-built snap to latest/stable channel
  .circleci/config.yml
  CONTRIBUTING.md
  ci/snap/README.md
  ci/snap/ci-deploy.sh
  ci/snap/ci-run.sh
  ci/snap/export-snapcraft-credentials
  snap/snapcraft.yaml
Labels: distribute, build, ci

#467 Issue #432: Do not print stack trace when handling `KeyboardInterrupt` exception
  git_machete/cli.py
Labels: bug

#472 Issue #424: Fix local-run.sh scripts so they can be executed from outside ci/<...> directory
  ci/checks/ensure-shell-scripts-pass-shellcheck.sh
  ci/deb-ppa-upload/local-run.sh
  ci/nixpkgs-build/local-run.sh
  ci/tox/local-run.sh
Labels: bug, ci
