Repository VirtusLab/git-machete, pull requests merged in 2022-05, with the labels that each got.

#507 Tests for `show`
  git_machete/tests/functional/commons.py
  git_machete/tests/functional/test_machete.py
  git_machete/tests/functional/test_show.py
Labels: code quality, testing

#510 Apply minor refactors in `def status`
  git_machete/client.py
Labels: code quality, status

#513 test `go`
  git_machete/tests/functional/test_go.py
  git_machete/tests/functional/test_machete.py
Labels: code quality, testing

#514 test `traverse` and `status`
  git_machete/tests/functional/commons.py
  git_machete/tests/functional/test_status.py
  git_machete/tests/functional/test_traverse.py
Labels: code quality, testing

#515 refactoring tests
  git_machete/tests/functional/__init__.py
  git_machete/tests/functional/test_clean.py
  git_machete/tests/functional/test_help.py
  git_machete/tests/functional/test_log.py
  tests/__init__.py
  tests/mockers.py
  tests/test_add.py
  tests/test_advance.py
  tests/test_clean.py
  tests/test_github.py
  tests/test_go.py
  tests/test_help.py
  tests/test_log.py
  tests/test_show.py
  tests/test_slide_out.py
  tests/test_squash.py
  tests/test_status.py
  tests/test_traverse.py
  tests/test_update.py
  tox.ini
Labels: code quality, testing

#516 rename `sha` to `hash` in variables/methods
  completion/git-machete.completion.zsh
  docs/source/cli_help/fork-point.rst
  git_machete/cli.py
  git_machete/client.py
  git_machete/docs.py
  git_machete/git_operations.py
Labels: code quality

#487 Issue #479: `git machete github *` should work with custom GitHub URL
  RELEASE_NOTES.md
  docs/source/cli_help/anno.rst
  docs/source/cli_help/clean.rst
  docs/source/cli_help/github.rst
  docs/source/conf.py
  docs/source/github_config_keys.rst
  git_machete/client.py
  git_machete/docs.py
  git_machete/git_operations.py
  git_machete/github.py
  tests/mockers.py
  tests/test_github.py
Labels: bug, github

#525 Issue #497: Parse branch name input from cli
  RELEASE_NOTES.md
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/options.py
  tests/mockers.py
  tests/test_add.py
  tests/test_anno.py
  tests/test_diff.py
  tests/test_fork_point.py
  tests/test_github.py
  tests/test_is_managed.py
  tests/test_log.py
  tests/test_show.py
  tests/test_traverse.py
Labels: bug, testing, cli

#538 Issue #527: Hide GitHub token value in `--debug` mode
  git_machete/utils.py
Labels: github, security

#532 Issue #528: Add docstrings in `mockers.py` to explain the most complicated mocks
  tests/mockers.py
Labels: docs, testing

#533 Issue #529: Increase CircleCI resource class to large for all the jobs
  .circleci/config.yml
Labels: performance
