Repository VirtusLab/git-machete, pull requests merged in 2022-08, with the labels that each got.

#613 Add missing `f`s to interpolated strings
  RELEASE_NOTES.md
  git_machete/__init__.py
  git_machete/client.py
Labels: bug, code quality

#620 Allow for editor arguments to be passed via git config/env vars
  RELEASE_NOTES.md
  git_machete/client.py
  git_machete/git_operations.py
Labels: bug, externally requested

#622 Fix warnings&errors across Sphinx docs
  RELEASE_NOTES.md
  docs/source/cli_help/config.rst
  docs/source/github_api_access.rst
  docs/source/github_config_keys.rst
  git_machete/__init__.py
  tox.ini
Labels: bug, docs, build

#624 Use fixed versions for all test/build packages
  .circleci/config.yml
  CONTRIBUTING.md
  requirements.coverage.txt
  requirements.docs.txt
  requirements.mypy.txt
  requirements.pep8.txt
  requirements.testenv.txt
  tox.ini
Labels: build, ci

#623 Add dependabot config
  .github/dependabot.yml
Labels: ci

#628 Split requirements files to work around dependabot issues
  requirements.mypy.py36-txt
  requirements.mypy.txt
  requirements.testenv.py36-txt
  requirements.testenv.txt
  tox.ini
Labels: dependencies

#630 Tidy up dependabot config
  .github/dependabot.yml
Labels: dependencies

#631 Issue #584: Update CONTRIBUTING.MD with info about conda-forge feedstock repo
  CONTRIBUTING.md
Labels: docs, distribute

#635 Issue #634: Improve `utils.warn()` function.
  git_machete/utils.py
Labels: code quality

#604 Issue #597: Handle Temporary Redirect when a repository or organization name was changed
  git_machete/github.py
Labels: bug, github

#632 Issue #618: Add new subcommand `git machete list childless`
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  completion/git-machete.fish
  docs/source/cli_help/list.rst
  git_machete/cli.py
  git_machete/client.py
  git_machete/docs.py
  tests/test_list.py
Labels: feature, externally requested

#639 Add `ci/checks/enforce-newline-at-eof.sh` + apply various minor fixes to shell scripts
  .circleci/config.yml
  CONTRIBUTING.md
  RELEASE_NOTES.md
  blogs/git-machete-1/blog.md
  blogs/git-machete-1/sandbox-setup-reduced.sh
  blogs/git-machete-1/sandbox-setup.sh
  blogs/git-machete-2/blog.md
  blogs/git-machete-2/sandbox-setup-2.sh
  ci/checks/enforce-completion-scripts-correct.sh
  ci/checks/enforce-consistent-style-for-fork-point.sh
  ci/checks/enforce-consistent-style-for-github.sh
  ci/checks/enforce-correct-shebangs.sh
  ci/checks/enforce-links-correct.sh
  ci/checks/enforce-newline-at-eof.sh
  ci/checks/enforce-release-notes-up-to-date.sh
  ci/checks/enforce-shell-scripts-pass-shellcheck.sh
  ci/checks/enforce-version-bumped.sh
  ci/checks/prohibit-trailing-whitespace.sh
  ci/checks/run-all-checks.sh
  ci/tox/local-run.sh
  debian/source/options
  git_machete/__init__.py
  graphics/setup-sandbox
Labels: docs, code quality, ci

#641 Simplify UID/GID handling in rpm Docker container with the use of `sudo`
  ci/ci-run-commons.sh
  ci/rpm/.gitignore
  ci/rpm/Dockerfile
  ci/rpm/build-context/entrypoint.sh
  ci/rpm/build-context/run.sh
  ci/rpm/ci-run.sh
  ci/rpm/docker-compose.yml
  ci/rpm/local-run.sh
Labels: code quality, ci

#642 Rectify `ci/nixpkgs-build` and `ci/deb-ppa-test-install`
  ci/deb-ppa-test-install/Dockerfile
  ci/deb-ppa-test-install/README.md
  ci/deb-ppa-test-install/build-context/entrypoint.sh
  ci/docker/Dockerfile
  ci/nixpkgs-build/ci-run.sh
  ci/nixpkgs-build/local-run.sh
Labels: code quality, ci

#643 Simplify UID/GID handling in deb-ppa-upload Docker container with the use of `sudo`
  .dockerignore
  blogs/docker-ci-tricks-2/blog.md
  ci/deb-ppa-upload/.gitignore
  ci/deb-ppa-upload/Dockerfile
  ci/deb-ppa-upload/build-context/entrypoint.sh
  ci/deb-ppa-upload/build-context/run.sh
  ci/deb-ppa-upload/ci-deploy.sh
  ci/deb-ppa-upload/docker-compose.yml
  ci/deb-ppa-upload/local-run.sh
  ci/docker-pull-or-build-and-push.sh
  ci/rpm/build-context/entrypoint.sh
  debian/.gitignore
  debian/source/options
Labels: code quality, ci
