Repository VirtusLab/git-machete, pull requests merged in 2023-02, with the labels that each got.

#802 Provide tests for GitHub API pagination
  tests/mockers.py
  tests/test_github.py
Labels: testing, github

#793 Add support for `slide-out=no` in branch qualifiers
  RELEASE_NOTES.md
  docs/source/cli_help/traverse.rst
  git_machete/annotation.py
  git_machete/client.py
  git_machete/generated_docs.py
  tests/mockers.py
  tests/test_traverse.py
Labels: feature, traverse

#810 Implement equivalent behaviour for `Q`->`ENTER` and `ENTER` inputs for `git-machete create-pr` command
  git_machete/client.py
Labels: bug

#800 Extract `GitHubClient` class
  RELEASE_NOTES.md
  git_machete/client.py
  git_machete/github.py
  tests/test_github.py
Labels: code quality

#809 Unify mocking method in tests
  tests/mockers.py
  tests/test_file.py
  tests/test_git_operations.py
  tests/test_github.py
  tests/test_help.py
Labels: code quality, testing

#811 Add test for GitHub Enterprise domain
  tests/mockers.py
  tests/test_github.py
Labels: testing, github

#813 Ensure no ancestor commit of parent branch is included into the branch's unique range of commits
  RELEASE_NOTES.md
  git_machete/client.py
  git_machete/git_operations.py
Labels: bug, fork point

#815 Fix zsh slide-out completion
  RELEASE_NOTES.md
  completion/git-machete.completion.zsh
  git_machete/__init__.py
Labels: bug, cli

#816 Fix GitHub token retrieval logic
  RELEASE_NOTES.md
  git_machete/github.py
Labels: bug, github

#818 Pass `--force` to `brew bump-formula-pr` to ignore open PRs in homebrew-core
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
  ci/pypi/ci-wait-for-package.sh
  git_machete/__init__.py
Labels: bug, distribute, ci

#822 Dry-run deploy to Homebrew: No available formula with the name "git-machete"
  ci/homebrew/ci-deploy.sh
Labels: bug, distribute

#825 Make `GitHubToken` class immutable
  git_machete/github.py
  tests/test_github.py
Labels: github

#828 Deprecate `machete.overrideForkPoint.<branch>.whileDescendantOf` key
  RELEASE_NOTES.md
  docs/source/cli_help/config.rst
  docs/source/cli_help/fork-point.rst
  git_machete/__init__.py
  git_machete/client.py
  git_machete/generated_docs.py
  git_machete/git_operations.py
  tests/test_fork_point.py
Labels: fork point
