Repository VirtusLab/git-machete, pull requests merged in 2023-01, with the labels that each got.

#759 Run `nix-build` in dry-run mode
  ci/nixpkgs-build/build-context/entrypoint.sh
Labels: bug, build

#752 Mock away undeterministic parts of `test_fmt`
  git_machete/utils.py
  tests/test_utils.py
Labels: bug, testing

#754 Implement pagination handling for GitHub API
  RELEASE_NOTES.md
  git_machete/client.py
  git_machete/github.py
  tests/mockers.py
  tests/test_github.py
Labels: bug, github

#756 Wait for PyPI package to be actually available after the upload
  .circleci/config.yml
  ci/pypi/ci-wait-for-package.sh
Labels: bug, distribute, ci

#766 Add missing completion for `t` alias of `traverse`
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  completion/git-machete.fish
Labels: bug, minor, cli

#743 Document local installation for development purposes in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: docs

#772 Ignore dependabot updates to sphinx (waiting for sphinx-rtd-theme 1.2.0)
  .github/dependabot.yml
Labels: build

#780 Fix API URL prefix for GitHub Enterprise
  RELEASE_NOTES.md
  git_machete/github.py
Labels: bug, github

#782 Explicitly install lxd via snap + fix shellcheck info-level issues
  ci/checks/enforce-shell-scripts-pass-shellcheck.sh
  ci/checks/enforce-version-bumped.sh
  ci/local-run-commons.sh
  ci/snap/ci-deploy.sh
Labels: bug, build

#783 Set up iptables for lxd to access internet on `ubuntu:22.04` CircleCI VM
  .circleci/config.yml
  ci/snap/ci-deploy.sh
Labels: bug, build

#785 Fix misc superfluous whitespace issues
  RELEASE_NOTES.md
  ci/checks/prohibit-strings-with-backslash-continuation.sh
  ci/checks/run-all-checks.sh
  git_machete/__init__.py
  git_machete/annotation.py
  git_machete/client.py
Labels: bug, status

#786 Tidy up Debian package upload process
  ci/deb-ppa-test-install/Dockerfile
  ci/deb-ppa-test-install/README.md
  ci/deb-ppa-test-install/docker-compose.yml
  ci/deb-ppa-upload/Dockerfile
  ci/deb-ppa-upload/build-context/dput.cf.envsubst
  ci/deb-ppa-upload/build-context/gpg-wrapper.sh
  ci/deb-ppa-upload/build-context/release-notes-to-changelog.awk
  ci/deb-ppa-upload/build-context/run.sh
  ci/deb-ppa-upload/ci-deploy.sh
  ci/deb-ppa-upload/docker-compose.yml
  ci/deb-ppa-upload/export-gpg-ssh-config
  ci/deb-ppa-upload/gpg-ssh.env
  ci/deb-ppa-upload/local-run.sh
Labels: code quality, distribute, build

#788 Add instructions for regenerating GPG keys for Launchpad and Snapcraft token
  ci/deb-ppa-upload/README.md
  ci/snap/README.md
  ci/snap/ci-deploy.sh
  ci/snap/export-snapcraft-credentials
Labels: docs, distribute, ci

#790 Improve docs for `machete.github.*` and other config keys
  RELEASE_NOTES.md
  docs/source/cli_help/config.rst
  docs/source/cli_help/format.rst
  docs/source/cli_help/status.rst
  docs/source/cli_help/traverse.rst
  docs/source/github_config_keys.rst
  docs/source/traverse_config_key.rst
  git_machete/generated_docs.py
Labels: docs

#795 Fix dry-run of Homebrew installation
  ci/homebrew/ci-deploy.sh
Labels: bug, distribute, build, ci

#792 Display branch names in `git-machete` command outputs and prompts with bolded formatting
  RELEASE_NOTES.md
  git_machete/cli.py
  git_machete/client.py
  git_machete/git_operations.py
  git_machete/github.py
  tests/test_github.py
Labels: code quality

#796 Revisit installation instructions in README
  README.md
  completion/README.md
Labels: docs, distribute

#799 Extract all of the git config keys as constants into separate file
  git_machete/cli.py
  git_machete/client.py
  git_machete/git_config_keys.py
  git_machete/git_operations.py
Labels: code quality
