Repository VirtusLab/git-machete, pull requests merged in 2023-04, with the labels that each got.

#866 Collect all known package badges into a single file
  BADGES.md
  README.md
Labels: docs

#860 Pass `--empty=drop` to the underlying `git rebase`
  RELEASE_NOTES.md
  git_machete/git_operations.py
  tests/test_update.py
Labels: bug, underlying git

#867 Replace `asciicast2gif` with `agg` in `graphics/generate-asciinema-gif`
  CONTRIBUTING.md
  graphics/bash-init-file
  graphics/discover-status-traverse.cast
  graphics/discover-status-traverse.gif
  graphics/generate-asciinema-gif
  graphics/setup-sandbox
Labels: docs

#869 Rerender gif from README, remove gaps between bars and junctions
  CONTRIBUTING.md
  RELEASE_NOTES.md
  git_machete/__init__.py
  graphics/discover-status-traverse.cast
  graphics/discover-status-traverse.gif
  graphics/generate-asciinema-gif
Labels: docs

#871 Release v3.16.3
  CONTRIBUTING.md
  RELEASE_NOTES.md
  git_machete/__init__.py
  graphics/discover-status-traverse.cast
  graphics/discover-status-traverse.gif
  graphics/generate-asciinema-gif
Labels: release

#872 Unify and fix usage of strict/inferred remote
  RELEASE_NOTES.md
  git_machete/__init__.py
  git_machete/client.py
  git_machete/git_operations.py
  tests/test_github.py
Labels: bug, traverse

#874 Run shellcheck based on shebang, not only .sh extension
  ci/checks/enforce-shell-scripts-pass-shellcheck.sh
  ci/deb-ppa-upload/export-gpg-ssh-config
  completion/git-machete.completion.bash
  hook_samples/machete-pre-rebase
Labels: code quality

#864 Do not assume that local branch and its remote counterpart has the same name when using `anno-prs`
  RELEASE_NOTES.md
  git_machete/client.py
  tests/mockers.py
  tests/test_github.py
Labels: bug, github

#878 Add `<branch>` parameter to `github retarget-pr` command
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  completion/git-machete.fish
  docs/source/cli_help/github.rst
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/generated_docs.py
  tests/test_github.py
Labels: feature, github

#884 Add `--ignore-if-missing` flag to `github retarget-pr` command
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  completion/git-machete.fish
  docs/source/cli_help/github.rst
  git_machete/cli.py
  git_machete/client.py
  git_machete/generated_docs.py
  tests/test_github.py
Labels: feature, github

#889 Do not checkout branches that are `untracked/ahead of remote/diverged from remote` in `traverse --no-push` mode
  git_machete/client.py
  tests/test_traverse.py
Labels: bug, traverse

#890 Remove `mogrify -loop 0` from `generate-asciinema-gif`
  CONTRIBUTING.md
  graphics/discover-status-traverse.cast
  graphics/discover-status-traverse.gif
  graphics/generate-asciinema-gif
Labels: docs

#875 Revamp `hook_samples/machete-post-slide-out` to take advantage of `git machete github retarget-pr`
  hook_samples/machete-post-slide-out
Labels: code quality, github

#891 Generate man page via Sphinx
  .circleci/config.yml
  .gitignore
  LICENSE
  MANIFEST.in
  RELEASE_NOTES.md
  ci/checks/enforce-consistent-style-for-fork-point.sh
  ci/checks/enforce-consistent-style-for-github.sh
  ci/checks/enforce-release-notes-up-to-date.sh
  ci/checks/prohibit-double-backticks-in-py.sh
  ci/checks/prohibit-markdown-links-in-rst.sh
  ci/checks/prohibit-single-backtick-in-rst.sh
  ci/checks/run-all-checks.sh
  ci/tox/.env-sample
  ci/tox/build-context/run.sh
  ci/tox/docker-compose.yml
  docs/enforce-py-docs-up-to-date.sh
  docs/enforce-sphinx-man-up-to-date.sh
  docs/generate-sphinx-html.sh
  docs/generate-sphinx-man.sh
  docs/man/git-machete.1
  docs/source/completion.rst
  docs/source/conf.py
  docs/source/index.rst
  docs/source/learning_materials.rst
  setup.py
  tox.ini
Labels: bug, docs

#894 Pin Homebrew version for `ci/homebrew/ci-deploy.sh`
  ci/checks/prohibit-strings-with-backslash-continuation.sh
  ci/homebrew/ci-deploy.sh
  ci/tox/.env-sample
  ci/tox/docker-compose.yml
  docs/man/git-machete.1
  docs/source/cli_help/github.rst
  git_machete/generated_docs.py
Labels: bug, distribute

#896 Fix fork point resolution when overridden fork point for branch X is an ancestor of X's parent
  RELEASE_NOTES.md
  docs/enforce-sphinx-man-up-to-date.sh
  docs/man/git-machete.1
  git_machete/__init__.py
  git_machete/client.py
Labels: bug, fork point

#900 Pass `--force-if-includes` to `git push` alongside `--force-with-lease` if git >= 2.30.0
  RELEASE_NOTES.md
  debian/source/options
  git_machete/git_operations.py
Labels: underlying git

#904 Take remote names into account when detecting remote branches in `git machete add`
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
  git_machete/client.py
  git_machete/git_operations.py
  graphics/setup-sandbox
  tests/mockers.py
  tests/test_add.py
  tests/test_github.py
  tox.ini
Labels: bug, underlying git

#907 Remove superfluous params from `tests.mockers.assert_command`
  tests/mockers.py
  tests/test_add.py
  tests/test_diff.py
  tests/test_fork_point.py
  tests/test_github.py
  tests/test_list.py
  tests/test_status.py
  tests/test_traverse.py
Labels: code quality, testing

#908 Extract the common `setup_method` to `BaseTest`
  tests/base_test.py
  tests/mockers.py
  tests/test_add.py
  tests/test_advance.py
  tests/test_anno.py
  tests/test_clean.py
  tests/test_client.py
  tests/test_diff.py
  tests/test_discover.py
  tests/test_file.py
  tests/test_fork_point.py
  tests/test_git_operations.py
  tests/test_github.py
  tests/test_go.py
  tests/test_help.py
  tests/test_is_managed.py
  tests/test_list.py
  tests/test_log.py
  tests/test_show.py
  tests/test_slide_out.py
  tests/test_squash.py
  tests/test_status.py
  tests/test_traverse.py
  tests/test_update.py
Labels: code quality, testing

#911 Use `vulture` to detect unused code
  .circleci/config.yml
  ci/ci-run-commons.sh
  ci/deb-ppa-upload/local-run.sh
  ci/nixpkgs-build/local-run.sh
  ci/rpm/local-run.sh
  ci/tox/build-context/run.sh
  ci/tox/local-run.sh
  git_machete/annotation.py
  git_machete/cli.py
  git_machete/constants.py
  git_machete/git_operations.py
  git_machete/utils.py
  requirements.vulture-check.txt
  tests/mockers.py
  tests/test_client.py
  tests/test_git_operations.py
  tests/test_update.py
  tox.ini
Labels: code quality, build

#914 Add tests for various uncovered commands & cases
  ci/docker/ci-deploy.sh
  git_machete/cli.py
  tests/__init__.py
  tests/mockers.py
  tests/test_anno.py
  tests/test_delete_unmanaged.py
  tests/test_fork_point.py
  tests/test_reapply.py
  tests/test_slide_out.py
  tests/test_traverse.py
  tests/test_update.py
  tests/test_version.py
  tox.ini
Labels: testing
