Repository VirtusLab/git-machete, pull requests merged in 2023-07, with the labels that each got.

#993 Use fish custom git command completion support
  completion/git-machete.fish
Labels: bug, cli

#997 Fix building the package for Ubuntu PPA
  RELEASE_NOTES.md
  ci/checks/enforce-bumped-version.sh
  ci/checks/run-all-checks.sh
  ci/deb-ppa-upload/build-context/run.sh
  debian/source/options
  docs/man/git-machete.1
  git_machete/__init__.py
Labels: bug, distribute, ci

#1000 Extract separate job for each deployment step in master CI
  .circleci/config.yml
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
Labels: distribute, ci
