Repository VirtusLab/git-machete, pull requests merged in 2023-03, with the labels that each got.

#834 Fix `strict_optional` mypy errors in tests
  git_machete/github.py
  mypy.ini
  tests/mockers.py
  tests/test_github.py
Labels: code quality, testing

#836 Fix `strict_optional` mypy errors in git_operations.py, github.py, utils.py
  git_machete/git_operations.py
  git_machete/github.py
  git_machete/utils.py
  mypy.ini
Labels: code quality, underlying git, github

#857 Fix `github create-pr` failing when the range of unique commits is empty
  git_machete/client.py
Labels: bug, github

#865 Do not re-annotate branches with the same annotation when using `github anno-prs`
  git_machete/client.py
Labels: minor, github
