Repository VirtusLab/git-machete, pull requests merged in 2023-05, with the labels that each got.

#916 Add missing tests for yellow-edge cases, among others
  git_machete/cli.py
  git_machete/client.py
  mypy.ini
  requirements.pep8.txt
  tests/base_test.py
  tests/mockers.py
  tests/test_delete_unmanaged.py
  tests/test_diff.py
  tests/test_discover.py
  tests/test_edit.py
  tests/test_file.py
  tests/test_fork_point.py
  tests/test_github.py
  tests/test_help.py
  tests/test_list.py
  tests/test_reapply.py
  tests/test_status.py
  tests/test_traverse.py
  tests/test_update.py
  tox.ini
Labels: code quality, testing

#920 Fix use from within venvs on Windows
  git-machete
  git_machete/bin.py
  mypy.ini
  setup.py
Labels: distribute

#923 Apply minor fixes before releasing v3.7.2
  .dockerignore
  RELEASE_NOTES.md
  ci/checks/enforce-indent-two-spaces-outside-python.sh
  git_machete/bin.py
  mypy.ini
  tox.ini
Labels: release

#924 Add missing tests + improve test code quality - vol. 3
  RELEASE_NOTES.md
  ci/pypi/ci-deploy.sh
  docs/man/git-machete.1
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/client.py
  git_machete/exceptions.py
  git_machete/git_operations.py
  requirements.isort.txt
  requirements.pep8.txt
  requirements.pypi-deploy.txt
  tests/base_test.py
  tests/mockers.py
  tests/test_add.py
  tests/test_advance.py
  tests/test_anno.py
  tests/test_clean.py
  tests/test_delete_unmanaged.py
  tests/test_diff.py
  tests/test_discover.py
  tests/test_edit.py
  tests/test_fork_point.py
  tests/test_git_operations.py
  tests/test_github.py
  tests/test_go.py
  tests/test_help.py
  tests/test_list.py
  tests/test_log.py
  tests/test_reapply.py
  tests/test_show.py
  tests/test_slide_out.py
  tests/test_squash.py
  tests/test_status.py
  tests/test_traverse.py
  tests/test_update.py
  tests/test_version.py
  tox.ini
Labels: code quality, testing

#929 Use sh instead of bash in tests
  tests/test_edit.py
  tests/test_status.py
Labels: testing

#933 Fill up release notes for 3.17.3
  RELEASE_NOTES.md
Labels: release

#937 Fix building HTML docs in CI and readthedocs.org build system
  .circleci/config.yml
  .readthedocs.yaml
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
  tox.ini
Labels: bug, docs

#942 Fix saving `.git/rebase-merge/author-script` + run CircleCI on Windows
  .circleci/config.yml
  RELEASE_NOTES.md
  git_machete/git_operations.py
  tests/base_test.py
  tests/mockers.py
  tests/test_update.py
Labels: bug, underlying git, windows

#934 Add missing tests - vol. 5
  git_machete/cli.py
  git_machete/client.py
  tests/test_fork_point.py
  tests/test_show.py
Labels: testing

#940 Make sure remote repos used in tests are always bare
  .circleci/config.yml
  RELEASE_NOTES.md
  tests/base_test.py
  tests/test_github.py
  tests/test_status.py
Labels: bug, testing

#944 Reorganize data on packages into a table
  BADGES.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  PACKAGES.md
  README.md
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
  tox.ini
Labels: docs, distribute

#948 Split `test_github.py` into separate files
  tests/mockers_github.py
  tests/test_github.py
  tests/test_github_anno_prs.py
  tests/test_github_checkout_prs.py
  tests/test_github_create_pr.py
  tests/test_github_retarget_pr.py
  tests/test_github_sync.py
  tox.ini
Labels: code quality, testing, github

#951 Run tests on macOS in CI
  .circleci/config.yml
Labels: ci, macos

#949 Fix the remaining tests for `github retarget-pr` on Windows
  .circleci/config.yml
  git_machete/client.py
  git_machete/github.py
  tests/mockers_github.py
  tests/test_github.py
  tests/test_github_checkout_prs.py
  tests/test_github_create_pr.py
  tests/test_github_retarget_pr.py
  tests/test_github_sync.py
Labels: bug, testing, ci, windows

#953 Bump base snap from `core18` to to `core22`
  snap/snapcraft.yaml
Labels: bug, ci

#954 Add missing tests - vol. 6
  RELEASE_NOTES.md
  git_machete/cli.py
  git_machete/client.py
  git_machete/git_operations.py
  tests/base_test.py
  tests/mockers_github.py
  tests/test_add.py
  tests/test_delete_unmanaged.py
  tests/test_fork_point.py
  tests/test_github.py
  tests/test_github_anno_prs.py
  tests/test_github_checkout_prs.py
  tests/test_github_create_pr.py
  tests/test_github_retarget_pr.py
  tests/test_github_sync.py
  tests/test_go.py
  tests/test_list.py
  tests/test_show.py
  tests/test_slide_out.py
  tests/test_squash.py
  tests/test_status.py
  tests/test_traverse.py
  tests/test_update.py
  tox.ini
Labels: bug, testing
