Repository VirtusLab/git-machete, pull requests merged in 2024-10, with the labels that each got.

#1344 Add a CI check against Python 3.13
  .circleci/config.yml
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
  git_machete/git_operations.py
  git_machete/utils.py
  tests/test_utils.py
Labels: distribute, ci

#1348 Fix release notes
  RELEASE_NOTES.md
Labels: release

#1349 Revert macOS job in CI
  .circleci/config.yml
Labels: ci, macos

#1352 Provide a GitHub PR title from `.git/info/title` file
  git_machete/client.py
  tests/test_github_create_pr.py
  tests/test_gitlab_create_mr.py
Labels: feature, github, gitlab

#1357 Revert simplifying requirements
  requirements/coverage.txt
  requirements/mypy.txt
  requirements/sphinx-docs.txt
  requirements/testenv.txt
  requirements/typos.txt
Labels: build, ci

#1355 Preload open PRs for updating PR descriptions
  docs/man/git-machete.1
  git_machete/client.py
Labels: code quality, github, gitlab

#1343 Update multiple PR/MR descriptions in bulk (`update-{pr,mr}-descriptions` subcommand)
  RELEASE_NOTES.md
  completion/git-machete.completion.bash
  completion/git-machete.completion.zsh
  completion/git-machete.fish
  docs/man/git-machete.1
  docs/source/cli/github.rst
  docs/source/cli/gitlab.rst
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/client.py
  git_machete/code_hosting.py
  git_machete/generated_docs.py
  tests/completion_e2e/test_completion_e2e.py
  tests/mockers_github.py
  tests/test_github.py
  tests/test_github_update_pr_descriptions.py
  tests/test_gitlab.py
  tests/test_gitlab_update_mr_descriptions.py
  tox.ini
Labels: feature, github, gitlab
