Repository VirtusLab/git-machete, pull requests merged in 2024-07, with the labels that each got.

#1275 Drop macOS pipelines from the CI
  .circleci/config.yml
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
Labels: ci, macos

#1278 Fix parsing multiline entries in git config
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/git_operations.py
  tests/test_git_operations.py
Labels: bug, underlying git

#1280 Limit log traversal for fork point to max 100 commits
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
  git_machete/client.py
  git_machete/constants.py
  git_machete/git_operations.py
  tests/test_go.py
  tests/test_traverse.py
Labels: performance, fork point

#1284 add installation instructions for `pex` utility
  README.md
Labels: docs, distribute

#1288 Update ISSUE_TEMPLATE.md
  ISSUE_TEMPLATE.md
Labels: docs

#1285 git {ref,}log calls: pass --no-show-signature
  RELEASE_NOTES.md
  git_machete/git_operations.py
  tests/test_git_operations.py
Labels: bug, underlying git
