Repository VirtusLab/git-machete, pull requests merged in 2024-09, with the labels that each got.

#1318 No longer publish Docker images from CI + reorganize CI checks
  .circleci/config.yml
  .readthedocs.yaml
  MANIFEST.in
  RELEASE_NOTES.md
  ci/docker/Dockerfile
  ci/docker/ci-deploy.sh
  ci/tox/.env-sample
  ci/tox/Dockerfile
  ci/tox/build-context/run.sh
  ci/tox/docker-compose.yml
  docs/man/git-machete.1
  git_machete/__init__.py
  tox.ini
Labels: distribute, ci

#1320 Replace `python setup.py` invocations with `python -m build`
  .github/dependabot.yml
  blogs/docker-ci-tricks-1/blog.md
  ci/ci-run-commons.sh
  ci/pypi/ci-deploy.sh
  ci/rpm/Dockerfile
  ci/rpm/build-context/run.sh
  ci/tox/Dockerfile
  ci/tox/build-context/requirements.txt
  ci/tox/build-context/run.sh
  requirements/pypi-deploy.txt
  tox.ini
Labels: build, ci

#1323 Skip RPM packages from GitHub releases
  .circleci/config.yml
  PACKAGES.md
  README.md
  RELEASE_NOTES.md
  ci/github-releases/ci-deploy.sh
  ci/pypi/ci-deploy.sh
  ci/rpm/Dockerfile
  ci/rpm/README.md
  ci/rpm/build-context/entrypoint.sh
  ci/rpm/build-context/run.sh
  ci/rpm/ci-run.sh
  ci/rpm/docker-compose.yml
  ci/rpm/local-run.sh
  requirements/pypi-publish.txt
Labels: distribute, ci

#1332 Use aware datetime instead of deprecated utcfromtimestamp
  git_machete/client.py
Labels: code quality

#1333 Work around the parsing bug in `git patch-id` v2.46.1
  .circleci/config.yml
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/git_operations.py
Labels: bug, underlying git

#1334 Fix 400 Bad Request in Test PyPI uploads
  ci/pypi/ci-deploy.sh
Labels: bug, distribute, ci

#1330 Make `create-{pr,mr}` take the existing `<!-- {start,end} git-machete generated -->` markers into account
  RELEASE_NOTES.md
  docs/man/git-machete.1
  docs/source/cli/github.rst
  docs/source/cli/gitlab.rst
  docs/source/git-config-keys/github_prDescriptionIntroStyle.rst
  docs/source/git-config-keys/gitlab_mrDescriptionIntroStyle.rst
  git_machete/client.py
  git_machete/generated_docs.py
  tests/test_github_create_pr.py
  tests/test_github_retarget_pr.py
  tests/test_gitlab_create_mr.py
  tests/test_gitlab_retarget_mr.py
Labels: bug, github, gitlab

#1337 Fix `pacman` invocation in Arch Linux package dry-run build
  ci/aur/Dockerfile
  ci/aur/build-context/entrypoint.sh
Labels: ci

#1338 Prevent outside env vars from leaking into tests in non-tox invocations
  tests/base_test.py
Labels: bug, testing

#1341 Fix docs for `config` (stray `gitlab-prs`)
  RELEASE_NOTES.md
  ci/checks/prohibit-github-in-gitlab-files.sh
  ci/checks/prohibit-github-mr-or-gitlab-pr.sh
  ci/checks/prohibit-gitlab-in-github-files.sh
  ci/checks/prohibit-mrs-in-github-files.sh
  ci/checks/prohibit-prs-in-gitlab-files.sh
  ci/checks/run-all-checks.sh
  docs/man/git-machete.1
  docs/source/cli/config.rst
  git_machete/generated_docs.py
Labels: docs, ci
