Repository VirtusLab/git-machete, pull requests merged in 2024-03, with the labels that each got.

#1193 Fix dry-run update of Homebrew formula
  ci/homebrew/ci-deploy.sh
Labels: bug, distribute, ci

#1194 Bump CI VMs
  .circleci/config.yml
  requirements/pypi-deploy.txt
  tox.ini
Labels: ci

#1195 Remove invocations of setup.py from non-Dockerized deployment code
  RELEASE_NOTES.md
  ci/checks/enforce-bumped-version.sh
  ci/checks/enforce-release-notes-up-to-date.sh
  ci/deb-ppa-upload/build-context/run.sh
  ci/docker/Dockerfile
  ci/docker/ci-deploy.sh
  ci/github-releases/ci-deploy.sh
  ci/homebrew/ci-deploy.sh
  ci/pypi/ci-wait-for-package.sh
  docs/man/git-machete.1
  git_machete/__init__.py
  snap/snapcraft.yaml
Labels: bug, distribute

#1198 Restore `brew tap homebrew/core` in `ci/homebrew/ci-deploy.sh`
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
  docs/man/git-machete.1
  git_machete/__init__.py
Labels: bug, distribute, ci

#1201 Release v3.24.2
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
  docs/man/git-machete.1
  git_machete/__init__.py
Labels: release

#1186 Add mentions of Scoop package in PACKAGES.md and README.md
  PACKAGES.md
  README.md
  RELEASE_NOTES.md
Labels: docs, distribute, ci

#1203 Revert `brew bump-formula-pr --write-only` in dry-runs of `brew bump-formula-pr`
  ci/homebrew/ci-deploy.sh
Labels: bug, distribute, ci

#1209 Allow setting per-branch update=merge option
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
  git_machete/annotation.py
  git_machete/client.py
  git_machete/options.py
  tests/test_traverse.py
  tests/test_update.py
Labels: feature, traverse
