Repository VirtusLab/git-machete, pull requests merged in 2024-04, with the labels that each got.

#1216 Bump PYTHON_VERSION for coverage on macOS
  .circleci/config.yml
Labels: ci

#1220 Use pytest-cov over coverage.py to enable pytest-xdist
  .circleci/config.yml
  .gitignore
  ci/homebrew/ci-deploy.sh
  requirements/coverage.txt
  requirements/mypy.txt
  setup.py
  tox.ini
Labels: performance, testing, ci

#1223 Make `git{hub,lab} restack-{pr,mr}` first retarget, then push
  RELEASE_NOTES.md
  git_machete/client.py
  tests/test_github_restack_pr.py
  tests/test_gitlab_restack_mr.py
Labels: github, usability, gitlab

#1225 Fix docs for `restack-{pr,mr}`
  docs/man/git-machete.1
  docs/source/cli/github.rst
  docs/source/cli/gitlab.rst
  git_machete/generated_docs.py
Labels: docs

#1227 Fix PyPI URL for Homebrew formula updates
  .circleci/config.yml
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
  ci/pypi/ci-wait-for-package.sh
  docs/man/git-machete.1
  git_machete/__init__.py
Labels: bug, severe, ci

#1228 Release v3.25.2
  .circleci/config.yml
  RELEASE_NOTES.md
  ci/homebrew/ci-deploy.sh
  ci/pypi/ci-wait-for-package.sh
  docs/man/git-machete.1
  git_machete/__init__.py
Labels: release

#1229 Fix incorrect re.sub invocation
  git_machete/utils.py
Labels: bug

#1231 Fix Homebrew dry-run formula updates
  ci/homebrew/ci-deploy.sh
Labels: bug, distribute, ci

#1233 Set --no-edit-merge flag automatically when using -y in traverse
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/cli.py
  tests/test_traverse.py
Labels: traverse
