Repository VirtusLab/git-machete, pull requests merged in 2024-05, with the labels that each got.

#1237 In `github create-pr`/`gitlab create-mr`, check whether base/target branch for PR/MR exists in remote, instead of fetching the entire remote
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/client.py
  git_machete/git_operations.py
  tests/test_github_create_pr.py
  tests/test_gitlab_create_mr.py
Labels: performance, github, gitlab

#1245 Enable verbose mode when `GIT_MACHETE_MEASURE_COMMAND_TIME` is set
  git_machete/utils.py
Labels: performance

#1248 Revert lost test coverage
  docs/man/git-machete.1
  git_machete/client.py
  hook_samples/post-commit
  tests/mockers.py
  tests/test_fork_point.py
  tests/test_github_checkout_prs.py
  tests/test_gitlab_checkout_mrs.py
  tests/test_status.py
  tox.ini
Labels: code quality, testing

#1255 Stop bumping Homebrew formula
  .circleci/config.yml
  PACKAGES.md
  ci/homebrew/ci-deploy.sh
  ci/pypi/ci-wait-for-package.sh
Labels: distribute, ci

#1238 Improve squash merge detection
  RELEASE_NOTES.md
  docs/man/git-machete.1
  docs/source/cli/config.rst
  docs/source/cli/slide-out.rst
  docs/source/cli/status.rst
  docs/source/cli/traverse.rst
  docs/source/cli/update.rst
  docs/source/git-config-keys/squashMergeDetection.rst
  git_machete/__init__.py
  git_machete/cli.py
  git_machete/client.py
  git_machete/constants.py
  git_machete/generated_docs.py
  git_machete/git_config_keys.py
  git_machete/git_operations.py
  git_machete/github.py
  git_machete/gitlab.py
  git_machete/options.py
  git_machete/utils.py
  tests/test_git_operations.py
  tests/test_help.py
  tests/test_status.py
  tests/test_traverse.py
Labels: status

#1258 Improve doc formatting
  docs/generate-sphinx-man.sh
  docs/man/git-machete.1
  docs/source/cli/add.rst
  docs/source/cli/advance.rst
  docs/source/cli/edit.rst
  docs/source/cli/file.rst
  docs/source/cli/fork-point.rst
  docs/source/cli/go.rst
  docs/source/cli/hooks.rst
  docs/source/cli/is-managed.rst
  docs/source/cli/list.rst
  docs/source/cli/show.rst
  docs/source/cli/slide-out.rst
  docs/source/cli/status.rst
  docs/source/cli/traverse.rst
  docs/source/index.rst
  docs/source/learning_materials.rst
  git_machete/cli.py
  tox.ini
Labels: docs, code quality

#1260 Bump version to 3.26.1
  RELEASE_NOTES.md
  docs/man/git-machete.1
  git_machete/__init__.py
  git_machete/client.py
  git_machete/git_config_keys.py
  git_machete/options.py
  tests/test_github_create_pr.py
  tests/test_gitlab_create_mr.py
Labels: code quality
