Repository VirtusLab/git-machete, pull requests merged in 2025-01, with the labels that each got.

#1384 Stop releasing packages to Ubuntu PPA
  .circleci/config.yml
  PACKAGES.md
  README.md
  RELEASE_NOTES.md
  ci/deb-ppa-test-install/Dockerfile
  ci/deb-ppa-test-install/README.md
  ci/deb-ppa-test-install/build-context/entrypoint.sh
  ci/deb-ppa-test-install/docker-compose.yml
  ci/deb-ppa-upload/Dockerfile
  ci/deb-ppa-upload/README.md
  ci/deb-ppa-upload/build-context/dput.cf.envsubst
  ci/deb-ppa-upload/build-context/entrypoint.sh
  ci/deb-ppa-upload/build-context/gpg-wrapper.sh
  ci/deb-ppa-upload/build-context/release-notes-to-changelog.awk
  ci/deb-ppa-upload/build-context/run.sh
  ci/deb-ppa-upload/ci-deploy.sh
  ci/deb-ppa-upload/docker-compose.yml
  ci/deb-ppa-upload/export-gpg-ssh-config
  ci/deb-ppa-upload/gpg-ssh.env
  ci/deb-ppa-upload/local-run.sh
  debian/.gitignore
  debian/compat
  debian/control
  debian/files.envsubst
  debian/rules
  debian/source/options
Labels: distribute, ci

#1385 Remove and prohibit current dates from expected test outputs
  ci/checks/prohibit-current-date-in-tests.sh
  ci/checks/run-all-checks.sh
  docs/man/git-machete.1
  tests/test_traverse_github.py
  tests/test_traverse_gitlab.py
  tests/test_utils.py
Labels: bug, testing

#1386 Release v3.32.0, attempt #2
  ci/checks/prohibit-current-date-in-tests.sh
  ci/checks/run-all-checks.sh
  docs/man/git-machete.1
  tests/test_traverse_github.py
  tests/test_traverse_gitlab.py
  tests/test_utils.py
Labels: release

#1387 Replace `list(map(fn, xs)` with `[fn(x) for x in xs]` for readability
  git_machete/cli.py
  git_machete/client.py
  git_machete/git_operations.py
  git_machete/utils.py
Labels: code quality

#1390 Tidy up naming in `SyncToParentStatus`
  git_machete/client.py
  git_machete/git_operations.py
  tests/test_status.py
Labels: traverse, status, usability

#1392 Unify test helpers access
  tests/base_test.py
  tests/completion_e2e/test_completion_e2e.py
  tests/mockers.py
  tests/mockers_git_repository.py
  tests/test_add.py
  tests/test_advance.py
  tests/test_anno.py
  tests/test_clean.py
  tests/test_client.py
  tests/test_delete_unmanaged.py
  tests/test_diff.py
  tests/test_discover.py
  tests/test_edit.py
  tests/test_file.py
  tests/test_fork_point.py
  tests/test_git_operations.py
  tests/test_github.py
  tests/test_github_anno_prs.py
  tests/test_github_checkout_prs.py
  tests/test_github_create_pr.py
  tests/test_github_restack_pr.py
  tests/test_github_retarget_pr.py
  tests/test_github_sync.py
  tests/test_github_update_pr_descriptions.py
  tests/test_gitlab.py
  tests/test_gitlab_anno_mrs.py
  tests/test_gitlab_checkout_mrs.py
  tests/test_gitlab_create_mr.py
  tests/test_gitlab_restack_mr.py
  tests/test_gitlab_retarget_mr.py
  tests/test_gitlab_update_mr_descriptions.py
  tests/test_go.py
  tests/test_help.py
  tests/test_is_managed.py
  tests/test_list.py
  tests/test_log.py
  tests/test_reapply.py
  tests/test_show.py
  tests/test_slide_out.py
  tests/test_squash.py
  tests/test_status.py
  tests/test_traverse.py
  tests/test_traverse_github.py
  tests/test_traverse_gitlab.py
  tests/test_update.py
Labels: code quality, testing
